// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	gopowerstore "github.com/dell/gopowerstore"
	mock "github.com/stretchr/testify/mock"
)

// AlertsClient is an autogenerated mock type for the AlertsClient type
type AlertsClient struct {
	mock.Mock
}

// GetAlerts provides a mock function with given fields: ctx, opts
func (_m *AlertsClient) GetAlerts(ctx context.Context, opts gopowerstore.GetAlertsOpts) (gopowerstore.Alerts, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetAlerts")
	}

	var r0 gopowerstore.Alerts
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, gopowerstore.GetAlertsOpts) (gopowerstore.Alerts, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, gopowerstore.GetAlertsOpts) gopowerstore.Alerts); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gopowerstore.Alerts)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, gopowerstore.GetAlertsOpts) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAlertsClient creates a new instance of AlertsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlertsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlertsClient {
	mock := &AlertsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
