// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	gopowerstore "github.com/dell/gopowerstore"
	mock "github.com/stretchr/testify/mock"
)

// EventsClient is an autogenerated mock type for the EventsClient type
type EventsClient struct {
	mock.Mock
}

// GetEvents provides a mock function with given fields: ctx, opts
func (_m *EventsClient) GetEvents(ctx context.Context, opts gopowerstore.GetEventsOpts) (gopowerstore.Events, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetEvents")
	}

	var r0 gopowerstore.Events
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, gopowerstore.GetEventsOpts) (gopowerstore.Events, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, gopowerstore.GetEventsOpts) gopowerstore.Events); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gopowerstore.Events)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, gopowerstore.GetEventsOpts) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEventsClient creates a new instance of EventsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventsClient {
	mock := &EventsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
