/*
 *
 * Copyright © 2021-2022 Dell Inc. or its subsidiaries. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	api "github.com/dell/gopowerstore/api"
	mock "github.com/stretchr/testify/mock"
)

// QueryParamsEncoder is an autogenerated mock type for the QueryParamsEncoder type
type QueryParamsEncoder struct {
	mock.Mock
}

// Async provides a mock function with given fields: _a0
func (_m *QueryParamsEncoder) Async(_a0 bool) api.QueryParamsEncoder {
	ret := _m.Called(_a0)

	var r0 api.QueryParamsEncoder
	if rf, ok := ret.Get(0).(func(bool) api.QueryParamsEncoder); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.QueryParamsEncoder)
		}
	}

	return r0
}

// Encode provides a mock function with given fields:
func (_m *QueryParamsEncoder) Encode() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Limit provides a mock function with given fields: _a0
func (_m *QueryParamsEncoder) Limit(_a0 int) api.QueryParamsEncoder {
	ret := _m.Called(_a0)

	var r0 api.QueryParamsEncoder
	if rf, ok := ret.Get(0).(func(int) api.QueryParamsEncoder); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.QueryParamsEncoder)
		}
	}

	return r0
}

// Offset provides a mock function with given fields: _a0
func (_m *QueryParamsEncoder) Offset(_a0 int) api.QueryParamsEncoder {
	ret := _m.Called(_a0)

	var r0 api.QueryParamsEncoder
	if rf, ok := ret.Get(0).(func(int) api.QueryParamsEncoder); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.QueryParamsEncoder)
		}
	}

	return r0
}

// Order provides a mock function with given fields: _a0
func (_m *QueryParamsEncoder) Order(_a0 ...string) api.QueryParamsEncoder {
	_va := make([]interface{}, len(_a0))
	for _i := range _a0 {
		_va[_i] = _a0[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 api.QueryParamsEncoder
	if rf, ok := ret.Get(0).(func(...string) api.QueryParamsEncoder); ok {
		r0 = rf(_a0...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.QueryParamsEncoder)
		}
	}

	return r0
}

// RawArg provides a mock function with given fields: _a0, _a1
func (_m *QueryParamsEncoder) RawArg(_a0 string, _a1 string) api.QueryParamsEncoder {
	ret := _m.Called(_a0, _a1)

	var r0 api.QueryParamsEncoder
	if rf, ok := ret.Get(0).(func(string, string) api.QueryParamsEncoder); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.QueryParamsEncoder)
		}
	}

	return r0
}

// Select provides a mock function with given fields: _a0
func (_m *QueryParamsEncoder) Select(_a0 ...string) api.QueryParamsEncoder {
	_va := make([]interface{}, len(_a0))
	for _i := range _a0 {
		_va[_i] = _a0[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 api.QueryParamsEncoder
	if rf, ok := ret.Get(0).(func(...string) api.QueryParamsEncoder); ok {
		r0 = rf(_a0...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.QueryParamsEncoder)
		}
	}

	return r0
}
